

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

kafka:
  topic:
    name: ${KAFKA_TOPIC_NAME:user-events}
    dlt-suffix: .DLT
  consumer:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    group-id: ${KAFKA_CONSUMER_GROUP_ID:my-consumer-group}
    auto-offset-reset: earliest
    enable-auto-commit: false
    max-poll-records: 10
    concurrency: 3
    backoff:
      max-retries: 3
      initial-interval: 1000
      multiplier: 2.0
      max-interval: 10000

logging:
  level:
    dev.perfectbogus.kafkaconsumer: DEBUG
    org.apache.kafka: WARN
